name: Build and Push Image to ECR

on: 
  push:
  workflow_dispatch:

jobs:
  aws_access_test:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
        id-token: write
        contents: read
    steps:
        - name: Configure AWS credentials 
          uses: aws-actions/configure-aws-credentials@v2
          with:
            role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
            aws-region: ${{ secrets.AWS_REGION }}
            
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download Code
  #       uses: actions/checkout@v3
  #     - name: Set Up Golang
  #       uses: actions/setup-go@v4
  #       with:
  #         go-version-file: go.mod
  #     - name: Run Test
  #       run: go test -v .
   
  # build:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps: 
  #     - name: Download Code
  #       uses: actions/checkout@v3
  #     - name: Set up Golang
  #       uses: actions/setup-go@v4
  #       with:
  #         go-version: '1.20'
  #     - name: Build
  #       run: go build -v .