name: Build and Push Image to ECR

on: 
  push:
  workflow_dispatch:

jobs:
  aws_access_test:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
        id-token: write
        contents: read
    steps:
        - name: Download Code
          uses: actions/checkout@v3
        - name: Set up Golang
          uses: actions/setup-go@v4
          with:
            go-version-file: go.mod
        - name: Configure AWS credentials 
          uses: aws-actions/configure-aws-credentials@v2
          with:
            role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
            aws-region: ${{ secrets.AWS_REGION }}
        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1

        - name: Build, tag, and push docker image to Amazon ECR
          env:
            REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            REPOSITORY: cloudterms-prod
            IMAGE_TAG: ${{ github.sha }}
          run: |
            docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
            docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        
            
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download Code
  #       uses: actions/checkout@v3
  #     - name: Set Up Golang
  #       uses: actions/setup-go@v4
  #       with:
  #         go-version-file: go.mod
  #     - name: Run Test
  #       run: go test -v .
   
  # build:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps: 
  #     - name: Download Code
  #       uses: actions/checkout@v3
  #     - name: Set up Golang
  #       uses: actions/setup-go@v4
  #       with:
  #         go-version: '1.20'
  #     - name: Build
  #       run: go build -v .