name: Build and Push Image to ECR

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  REGISTRY: ${{ steps.login-ecr.outputs.registry }}
  REPOSITORY: ${{ secrets.DEV_ECR_REPO }}
  IMAGE_TAG: ${{ github.sha }}
  IMAGE_REF: ${{ env.REGISTRY }}/${{ secrets.DEV_ECR_REPO }}:${{ env.IMAGE_TAG }}

jobs:
  build_and_push_image:
    environment: Development
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download Code
        uses: actions/checkout@v3

      - name: Set up Golang
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Unit Test
        run: go test -v .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Tag Docker Image
        id: build_step
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v1
        with:
          image-ref: ${{ env.IMAGE_REF }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Push Docker image to Amazon ECR
        run: |
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
