name: Build and Push Image to ECR Prod Repo

on: 
  push:
    branches: 
      - main
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  if_merged_push_image:
    if:  github.event.pull_request.merged == true || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    environment: Production
    runs-on: ubuntu-latest

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
        id-token: write
        contents: read
    steps:
        - name: Download Code
          uses: actions/checkout@v3

        - name: Set up Golang
          uses: actions/setup-go@v4
          with:
            go-version-file: go.mod

        - name: Configure AWS credentials 
          uses: aws-actions/configure-aws-credentials@v2
          with:
            role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1

        - name: Build, tag, and push docker image to Amazon ECR
          env:
            REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            REPOSITORY: ${{ vars.PROD_ECR_REPO }}
            IMAGE_TAG: ${{ github.sha }}
          run: |
            docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
            docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        
            
